### ISSUE TITLE
Maximum Likelyhood Estimation

### ISSUE THREAD

**Issue by davidkowalk** [davidkowalk/fitting_toolkit#20]
Provide fit options for curve fitting via maximum likelyhood estimation

**Comment by davidkowalk** [comment]
- 1fbd1a217d3c93f01cccd159e954a82595fadfd8 specifies algorithm
- 52a932477b11052a8082d5e27091e44d0d4621d0 implements log likelyhood per point
- 4b511031f9a64df3a7c9cab38b0dc72f5972074e implements log likelyhood for model, minimizes via `scipy.optimize.minimize`

Changes are untested

**Comment by davidkowalk** [comment]
When providing an xerror the following error message is produced:
```
Traceback (most recent call last):
  File "<python-input-21>", line 1, in <module>
    params, cov = curve_fit(f, x, y, yerror=dy, xerror = dx)
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\Programming General\fitting_toolkit\src\fit.py", line 75, in curve_fit_mle
    result = minimize(neg_log_likelyhood, theta_0, args=(model, xdata, ydata, yerror, xerror))
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\optimize\_minimize.py", line 726, in minimize
    res = _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\optimize\_optimize.py", line 1371, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
                                  finite_diff_rel_step=finite_diff_rel_step)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\optimize\_optimize.py", line 288, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
                        finite_diff_rel_step, bounds, epsilon=epsilon)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 222, in __init__
    self._update_fun()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 294, in _update_fun
    fx = self._wrapped_fun(self.x)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 20, in wrapped
    fx = fun(np.copy(x), *args)
  File "C:\Users\User\Documents\Programming General\fitting_toolkit\src\fit.py", line 50, in neg_log_likelyhood
    return np.sum(neg_log_likelihood_per_point_xyerr(model, theta, x, y, xerror, yerror))
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\Programming General\fitting_toolkit\src\fit.py", line 24, in neg_log_likelihood_per_point_xyerr
    integral, _ = quad(integrand, -np.inf, np.inf)
                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\integrate\_quadpack_py.py", line 459, in quad
    retval = _quad(func, a, b, args, full_output, epsabs, epsrel, limit,
                   points)
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\integrate\_quadpack_py.py", line 608, in _quad
    return _quadpack._qagie(func, bound, infbounds, args, full_output,
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            epsabs, epsrel, limit)
                            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: only length-1 arrays can be converted to Python scalars
```

**Comment by davidkowalk** [comment]
4caf00163461bccb9795577b08848e0ddd19256d corrects this by vectorizing the function
8e3039422ed0053266a62980e6de13503d704569 integrates into curve_fit function

**Comment by davidkowalk** [comment]
a3497077c9775f7f8ca3ca08fcb27704f1f2d107 Integrates peak fitting with MLE
documentation required

**Comment by davidkowalk** [comment]
Required Documentation:

**Technical documentation**
- [x] update curve_fit()
- [x] fit.neg_log_likelihood_per_point_yerr()
- [x] fit.neg_log_likelihood_per_point_xyerr()
- [x] fit.neg_log_likelyhood()
- [x] fit.curve_fit_mle()
- [x] fit.neg_log_event_likelyhood()
- [x] fit.fit_distribution_mle()

**Tutorials**
- [x] Curve Fit with MLE
- [x] Peak Fit with MLE
- [x] Using MLE Subfunctions
